"""1st barber added it barbers table 

Revision ID: 27f7ee66d17d
Revises: 2620575a9195
Create Date: 2025-03-14 11:24:42.909375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f7ee66d17d'
down_revision: Union[str, None] = '2620575a9195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
