"""Fixed auto-increment issue on barbers table

Revision ID: d99beb42c844
Revises: 27f7ee66d17d
Create Date: 2025-03-14 11:32:11.557011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99beb42c844'
down_revision: Union[str, None] = '27f7ee66d17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
